apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-rc
spec:
  replicas: 3
  selectors:
     app: mynginx
  template:
    metadata:
       labels:
          app: mynginx
    spec:
      containers:
      - name: hello-pod container
        image: nginx
        ports:
         - containerPort: 80        
  
