apiVersion: v1
kind: Service
metadata:
  name: mynginx-svs
  labeles:
       app: mynginx
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocal: TCP
  selector:
      app: mynginx     

