apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
spec:
  type: NodePort
  containers:
    - name: first-container
      image: nginx
      ports:
      - containerPort: 80  
        nodePort: 30001
        protocol: TCP