apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  name: nodeport-services
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  type: NodePort
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
  ports:
    - protocol: TCP
      port: 80
      targetPort: 30002
      nodePort: 30002
